

# Database
# user: admin, pwd: mariamleokevser
services:

  backend:
    build: ./backend
    container_name: jibjob-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:16
    container_name: jibjob-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/migrations/000001_create_profiles_table.up.sql:/docker-entrypoint-initdb.d/01_profiles.sql:ro
      - ./database/migrations/000002_create_questions_table.up.sql:/docker-entrypoint-initdb.d/02_questions.sql:ro
      - ./database/migrations/000003_create_questionnaire_answers_table.up.sql:/docker-entrypoint-initdb.d/03_questions_answers.sql:ro
      - ./database/migrations/000004_create_certification_results_table.up.sql:/docker-entrypoint-initdb.d/04_certification_results.sql:ro
      - ./database/migrations/000005_create_consents_table.up.sql:/docker-entrypoint-initdb.d/05_consents.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  postgres-data:
