package main

var questionsAPoser = []Question{
	{Content: "Je respecte toujours les horaires convenus.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime travailler en équipe.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'adapter rapidement à un nouvel environnement.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je termine toujours ce que je commence.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais demander de l'aide quand j'en ai besoin.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'accepte volontiers les critiques constructives.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je me fixe des objectifs clairs dans mon travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime relever de nouveaux défis.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je reste motivé même face à des tâches répétitives.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je communique facilement avec mes collègues.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte les règles et procédures de l'entreprise.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de gérer plusieurs tâches en même temps.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je prends des initiatives sans qu'on me le demande.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je reste calme dans les situations stressantes.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime apprendre de nouvelles compétences.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis ponctuel(le) à mes rendez-vous professionnels.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais organiser mon temps de travail efficacement.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis honnête avec mes collègues et supérieurs.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime aider les autres dans leur travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de travailler de façon autonome.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte les délais qui me sont fixés.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis à l'aise pour parler en public.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais reconnaître mes erreurs et en tirer des leçons.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime avoir des responsabilités.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je m'implique pleinement dans les projets qu'on me confie.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de résoudre des problèmes de façon autonome.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je m'entends généralement bien avec mes collègues.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis motivé(e) par l'idée de progresser professionnellement.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je fais preuve de patience face aux difficultés.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à sortir de ma zone de confort.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais garder la confidentialité des informations sensibles.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je m'adapte facilement aux changements d'organisation.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de prioriser mes tâches efficacement.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je fais preuve de rigueur dans mon travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime partager mes connaissances avec les autres.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de travailler sous pression.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte les opinions différentes des miennes.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais rester professionnel(le) en toute circonstance.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à faire des efforts supplémentaires si nécessaire.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je crois en l'importance du travail bien fait.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis quelqu'un de fiable sur qui on peut compter.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime comprendre le sens de mon travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais m'exprimer clairement à l'écrit.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'auto-évaluer objectivement.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte la hiérarchie tout en donnant mon avis.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis motivé(e) à long terme dans mes projets.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais garder mon calme face à un désaccord.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'organiser sans supervision constante.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime travailler dans un environnement structuré.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à me former pour évoluer dans mon métier.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère l'honnêteté comme une valeur essentielle au travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais m'entourer de personnes compétentes.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de gérer une charge de travail importante.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime comprendre les attentes avant de commencer une tâche.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je fais preuve de persévérance face à l'échec.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte le travail et le temps des autres.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'intégrer rapidement dans une équipe.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère la ponctualité comme importante.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis motivé(e) par l'atteinte d'objectifs concrets.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais accepter de ne pas toujours avoir raison.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de rester concentré(e) longtemps sur une tâche.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime contribuer à un objectif commun.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis à l'aise pour poser des questions si je ne comprends pas.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère le respect mutuel comme fondamental au travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'adapter à différents interlocuteurs.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais gérer mon stress avant une échéance importante.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à changer d'avis si les arguments sont convaincants.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime avoir un cadre de travail clair.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de proposer des solutions à un problème.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère la loyauté comme une valeur importante.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais travailler avec des personnes différentes de moi.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis motivé(e) à me dépasser dans mon travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte les engagements que je prends.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de gérer une déception professionnelle.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime comprendre le fonctionnement global d'une entreprise.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère la transparence comme essentielle.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'exprimer avec assurance.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais reconnaître le travail des autres.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à m'investir sur le long terme.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère l'esprit d'équipe comme indispensable.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'auto-discipliner.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime avoir un retour sur la qualité de mon travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis motivé(e) par le sentiment d'utilité.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je respecte les valeurs de l'entreprise qui m'emploie.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de gérer un imprévu sans paniquer.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère le respect des délais comme une priorité.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais m'adapter à un rythme de travail soutenu.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de collaborer avec des services différents.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "J'aime que mon travail ait un impact concret.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère l'écoute comme une qualité essentielle.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à accepter des tâches en dehors de mes attributions habituelles.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de faire preuve de diplomatie.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère la motivation comme un moteur essentiel de la réussite.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je sais garder une attitude positive face aux difficultés.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis capable de m'engager pleinement dans un projet.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère le sérieux comme une qualité professionnelle clé.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis motivé(e) à l'idée de rejoindre une nouvelle équipe.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère que le travail bien fait mérite d'être reconnu.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je suis prêt(e) à donner le meilleur de moi-même au travail.", Options: []string{"Oui", "Non"}, Weight: 1},
	{Content: "Je considère que le respect des consignes est important.", Options: []string{"Oui", "Non"}, Weight: 1},
}